services:
  server:
    image: library-backend
    build:
      context: .
      dockerfile: library-backend/Dockerfile
    ports:
      - 4000:4000
    container_name: library_backend
  app:
    image: library-frontend
    build:
      context: .
      dockerfile: library-frontend/Dockerfile
    ports:
      - 3000:3000
    container_name: library-frontend
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server
